In [ ]:
import cv2
import numpy as np
 
if __name__ == '__main__' :
 
    # Read image
    im = cv2.imread("./data/2.png")
    print(im) 
    # Select ROI
    r = cv2.selectROI(im)
    #print(r)
    # Crop image
    imCrop = im[int(r[1]):int(r[1]+r[3]), int(r[0]):int(r[0]+r[2])]
 
    # Display cropped image
    cv2.imshow("Image", imCrop)
    cv2.waitKey(0)

[[[221 224 222]
  [221 224 222]
  [222 225 223]
  ...
  [223 224 219]
  [223 224 219]
  [223 224 219]]

 [[221 224 222]
  [221 224 222]
  [222 225 223]
  ...
  [223 224 219]
  [223 224 219]
  [223 224 219]]

 [[221 224 222]
  [221 224 222]
  [222 225 223]
  ...
  [224 225 220]
  [224 225 220]
  [224 225 220]]

 ...

 [[196 205 199]
  [196 206 199]
  [182 194 186]
  ...
  [236 236 234]
  [235 235 233]
  [235 235 233]]

 [[200 201 201]
  [200 203 203]
  [197 203 198]
  ...
  [236 236 234]
  [235 235 233]
  [235 235 233]]

 [[202 202 202]
  [202 203 203]
  [200 203 201]
  ...
  [236 236 234]
  [235 235 233]
  [235 235 233]]]
